name: Rien de spécial
title: Rien de spécial
description: Le blog de Régis
lang: fr-FR
theme: jekyll-theme-slate
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
permalink: "/blog/:year/:month/:title"
disqus_id: "/blog/:year/:month/:title"
google_analytics: UA-78978-1
paginate: 5
paginate_path: "/blog/page/:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
github:
  owner_name: Régis
  owner_url: https://plus.google.com/+RégisDécamps
author: Régis
social:
  name: Régis
  links:
    - https://plus.google.com/+R%C3%A9gisD%C3%A9camps
    - https://www.facebook.com/regis.decamps
  gplus: https://plus.google.com/+R%C3%A9gisD%C3%A9camps
  fb: https://www.facebook.com/regis.decamps
