name: Rien de spécial
title: Rien de spécial
description: Le blog de Régis
lang: fr-FR
theme: jekyll-theme-slate
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
permalink: "/blog/:year/:month/:title"
disqus_id: "/blog/:year/:month/:title"
google_analytics: 78978-1
