url: http://regis.decamps.info/blog/
name: Rien de spécial
title: Rien de spécial
description: Le blog de Régis
theme: jekyll-theme-slate
permalink: /blog/:year/:month/:title
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
google_analytics: 78978-1
